openapi: 3.0.0
info:
  description: Star Wars Planets API
  version: 1.0.0
  title: Example
servers:
  - url: https://swapi-golang-rest-api.herokuapp.com/api
    description: Server address
tags:
  - name: "SWAPI Golang REST API Challenge"
paths:
  /planets/{planetID}:
    get:
      operationId: "getPlanet"
      summary: Get Planet
      description: Gets an existing planet by its ID
      parameters: 
        - name: planetID
          in: path
          description: Planet ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListingPlanet"
              example:       
                id: 5f877f2a77fe0165cb16202b
                name: tatooine
                climate: arid
                terrain: desert
                appearances: 5
        "404":
          description: "Not Found"
  /planets:
    get:
      operationId: "listPlanets"
      summary: List Planets
      description: Lists existing planets
      parameters:
        - name: limit
          in: query
          description: "Determines the maximum number of planets to be returned in this page"
          required: false
          schema:
            type: integer
            default: 20
            minimum: 0
        - name: page
          in: query
          description: "Determines which page to show"
          required: false
          schema:
            type: integer
            default: 1
            minimum: 1
      responses:
        "200":
          description: "OK"
          headers:
            X-Total-Count:
              description: Total count of resources despite the page limit
              schema:
                type: string
              example:
                X-Total-Count: 234
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ListingPlanet"
                example:
                  - id: "5f877f2a77fe0165cb16202b"
                    name: "tatooine"
                    climate: "arid"
                    terrain: "desert"
                    appearances: 5
                  - id: "5f87801877fe0165cb16202c"
                    name: "alderaan"
                    climate: "temperate"
                    terrain: "grasslands"
                    appearances: 2
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
    post:
      summary: Add Planet
      description: Adds a new planet
      operationId: addPlanet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddingPlanet'
            example:
              name: "tatooine"
              climate: "arid"
              terrain: "desert"
      responses:
        "201":
          description: "Created"
          headers:
            Location:
              description: "Relative URL from the Request URL to access the created resource. e. g.: \"Location\": \"/5f877f2a77fe0165cb16202b\""
              schema:
                type: string
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                type: object
                required:
                    - message
                properties:
                    message:
                      type: string
              example:
                message: validation error
                fields:
                  name: Missing required field
        "500":
          description: "Internal server error"
components:
  schemas:
    BadRequestError:
      type: object
      properties:
        message:
          type: string
      example:
        message: "offset value must be an integer. got: \"foo\""
    ValidationError:
      type: object
      required:
        - message
        - fields
      properties:
          message:
            type: string
          fields:
            type: array
            items:
              type: object
    ListingPlanet:
      type: object
      required:
        - id
        - name
        - climate
        - terrain
      properties:            
        id:
          type: string
        name:
          type: string
        climate:
          type: string
        terrain:
          type: string
        appearances:
          type: number
    AddingPlanet:
      type: object
      required:
        - name
        - climate
        - terrain
      properties:            
        name:
          type: string
        climate:
          type: string
        terrain:
          type: string